INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(panasonic, 800, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Sony, 700, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Apple, 1000, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Sony Notebook, 1000, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Hewlet Packard, 500, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Bianchi, 1500, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Nke, 900, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Adidas, 1800, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Reebook, 1200, 'ematz',now(()))
INSERT INTO productos (nombre,precio,usuario_creacion,fecha_creacion)VALUES(Puma, 4 00, 'ematz',now(()))